#+TITLE: Pacman a AUR Helpers
#+DESCRIPTION: Správce balíčků Pacman a pomocníci pro správu AUR
#+AUTHOR: Antonin Fischer (raven2cz)
#+STARTUP: inlineimages
#+EXPORT_FILE_NAME: /home/box/org/export/pacman-aur-helpers.org
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>
#+HTML_HEAD: <style> li{max-width:800px;}</style

* Obsah :toc:
- [[#pacman][Pacman]]
  - [[#první-krůčky][První krůčky]]
  - [[#pacman-configuration-etcpacmanconf][Pacman Configuration /etc/pacman.conf]]
  - [[#pacman-repositories-multilib-extra-community-a-úrověň-testing][Pacman Repositories multilib, extra, community a úrověň testing]]
- [[#aur-arch-user-repository][AUR (Arch User Repository)]]
  - [[#yay-paru-aura-pomocníci-aur][Yay, Paru, Aura pomocníci AUR]]
- [[#důležité-odkazy][Důležité odkazy]]

* Pacman
** První krůčky
[[https://wiki.archlinux.org/title/pacman][Pacman-Arch-Wiki
]]
Správce balíků =pacman= je jednou z hlavních charakteristických vlastností *Arch Linuxu*. Kombinuje jednoduchý binární formát balíčku se snadno použitelným sestavovacím systémem (build system). Cílem pacmanu je umožnit snadnou správu balíčků, ať už jsou z oficiálních úložišť, nebo z vlastních sestavení uživatele.

Pacman udržuje systém aktuální synchronizací seznamů balíků s hlavním serverem. Tento model server/klient také umožňuje uživateli stahovat/instalovat balíčky jednoduchým příkazem, doplněný o všechny požadované závislosti.

Pacman je napsán v programovacím jazyce C a používá BSD tar formát pro balení.

#+BEGIN_SRC bash
sudo pacman -S awesome ## install package/meta-package
sudo pacman -Syu ## System update
sudo pacman -Syy ## sync database
pacman -Ss gnome ## search package with text 'gnome'
pacman -Qs gnome ## search installed packages
pacman -Si plasma ## display extensive information
pacman -Qii gnome ## info + list of backup files
pacman -Qdt ## list packages no longer reqs (orphans)
sudo pacman -Sc ## clear packages in cached packages
sudo pacman -Scc ## all files in cache, strong aggresive, nothing leave in cache
sudo pacman -U /path/to/package/package_name-version.pkg.tar.zst #@ install local pckage, from AUR
sudo pacman -S --asdeps unzip ## install as dependency, can be removed as orphans
sudo pacman -Qe mc ## list version if it is explicitly installed
sudo pacman -D --asdeps unzip ## change the status to deps
sudo pacman -D --asexplicit unzip
sudo pacman -F pacman ## search files which are containing by package
sudo pacman --needed base-devel ## install if necessary
pactree awesome ## tree of depended packages
#+END_SRC

** Pacman Configuration /etc/pacman.conf
Moje nastavení s barvami, přehlednou tabulkou stažení balíčků, opravodovým pacmanem a paralelním stahováním.
#+BEGIN_SRC bash
Color
CheckSpace
VerbosePkgLists
ILoveCandy
ParallelDownloads = 5
#+END_SRC

Bezpečnost a gpg podepisování: ~SigLevel = Required DatabaseOptional~
Pacman podporuje podpisy balíčků, které do balíků přidávají další vrstvu zabezpečení. Výchozí konfigurace, ~SigLevel = Required DatabaseOptional~, umožňuje ověření podpisu pro všechny balíčky na globální úrovni.

Nikdy nepoužívejte ~SigLevel = Never~ (jen zcela v případě velké nouze, nebo člověka, kterého skutečně znáte a jeho závislost nelze obnovit kvůli nemoci například.)

** Pacman Repositories multilib, extra, community a úrověň testing
Může se také stát, že úložiště obsahující balíček není ve vašem systému povoleno, např. Balíček může být v multilib úložišti, ale multilib není povolen ve vašem pacman.conf. Nutno povolit.

Můžete se stát i testerem pro Arch. Zapnout balíčky s =-testing=. Nutno pak ale updatovat celý systém, není jednoduchá změna! Pozor.

* AUR (Arch User Repository)
*Arch User Repository (AUR)* je komunitní úložiště pro uživatele Arch. Obsahuje popisy balíků ( PKGBUILDs ), které vám umožňují sestavit balíček ze zdroje pomocí =makepkg= a poté jej nainstalovat pomocí pacman. AUR byla vytvořena za účelem organizace a sdílení nových balíčků z komunity a za účelem urychlení začlenění oblíbených balíčků do úložiště komunity.

Mnoho nových balíčků, které vstupují do oficiálních úložišť, začíná v AUR. V AUR mohou uživatelé přispívat svými vlastními sestavami balíků (PKGBUILDa související soubory). Komunita AUR má možnost hlasovat pro balíčky v AUR. Pokud se balíček stane dostatečně populárním - za předpokladu, že má kompatibilní licenci a dobrou techniku ​​balení - může být vložen do komunitního úložiště (přímo přístupného pacmanem nebo abs).

*Varování:* Balíčky AUR jsou uživatelsky vytvářený obsah. Tyto PKGBUILDjsou zcela neoficiální a nebyli důkladně prověřeni. Jakékoli použití poskytnutých souborů je na vaše vlastní riziko.

** Yay, Paru, Aura pomocníci AUR
- [[https://github.com/Jguer/yay][JGuer/yay]] - Yet Another Yogurt - An AUR Helper napsán v Go
- [[https://github.com/Morganamilo/paru][Morganamilo/paru]] - Paru AUR pomocník s mnoho features a minimální interakcí. Napsán Rust.
- [[https://github.com/fosskers/aura][fosskers/aura]] - Nadstandardní služby, zajímavé funkce, downgrades a zabezpečení upgrades a snapshots ovládání. Napsáno v Haskell.

*** Paru instalace
#+BEGIN_SRC bash
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
#+END_SRC

*** Paru příklady užití
+ ~paru <target>~ - Interaktivně vyhledávejte a instalujte <target>.
+ ~paru~ - Alias ​​pro paru -Syu.
+ ~paru -S <target>~ - Nainstalujte si konkrétní balíček.
+ ~paru -Sua~ - Upgradujte balíčky AUR.
+ ~paru -Qua~ - Vytiskněte dostupné aktualizace AUR.
+ ~paru -G <target>~ - Stáhněte si PKGBUILD a související soubory z <target>.
+ ~paru -Gp <target>~ - Vytiskněte PKGBUILD z <target>.
+ ~paru -Gc <target>~ - Vytiskněte si komentáře AUR pro <target>.
+ ~paru --gendb~ - Vytvořte databázi devel pro sledování *-gitbalíčky. To je potřeba pouze tehdy, když zpočátku používáte paru.
+ ~paru -Ui~ - Vytvořte a nainstalujte PKGBUILD do aktuálního adresáře.

*** Aura instalace
#+BEGIN_SRC bash
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin
makepkg
sudo pacman -U <the-package-file-that-makepkg-produces>
#+END_SRC

*** Aura zajímavé příkazy
+ ~aura -Pa~ - Analyzujte všechny místně nainstalované balíčky AUR.
+ ~aura -O~ - Zobrazit osiřelé balíčky.
+ ~aura -L~ - Zobrazit protokol Pacman.
+ ~aura -Li <package>~ - Zobrazit historii instalace / upgradu balíčku.
+ ~aura -Cc <n>~ - Odstranit všechny kromě nejnovější nverze každého balíčku uloženého v mezipaměti.
+ ~aura -C <package>~ - Downgrade balíčku.
+ ~aura -Cv~ - Odstranit všechny /var/cache/aura/vcsmezipaměti
+ ~aura -B~ - Uložte záznam JSON všech nainstalovaných balíčků.
+ ~aura -Br~ - Obnovte uložený záznam. Podle potřeby se vrací zpět a odinstaluje.
+ ~aura -Bc <n>~ - Odstranit všechny kromě nejnovější nuložené státy.
+ ~aura -Bl~ - Zobrazit všechny uložené názvy souborů stavu balíčku.
+ ~aura -Au~ - Upgradujte všechny nainstalované balíčky AUR.
+ ~aura -Akuax~ - Oblíbený autor (upgrady, odstranění makedeps, ukazuje rozdíly PKGBUILD, ukazuje postup)
+ ~aura -As <regex>~ - Hledejte AUR pomocí regexu.
+ ~aura -Ap <package>~ - Zobrazit balíček PKGBUILD.
+ ~aura -Ad <package>~ - Seznam závislostí balíčku.

* Důležité odkazy
+ [[https://www.youtube.com/user/tondafischer/featured][Youtube Channel TUX: Svět Linuxu]]
+ [[https://archlinux.org/][archlinux.org]]
+ [[https://wiki.archlinux.org/][wiki.achlinux.org]]
+ [[https://fishlive.org/en/blog-tech-art/arch][fishlive.org/blog]]
+ [[https://github.com/raven2cz/tux][github/raven2cz/tux]]
+ [[https://github.com/raven2cz/dotfiles][github/raven2cz/dotfiles]]
